bugfix - attempt to fix release GitHub Action error
```
[main 32b1b8b] Cut Release 'v2024.5.23'
 3 files changed, 12 insertions(+), 4 deletions(-)
 delete mode 100644 .changes/unreleased/Bugfix-20240523-114929.yaml
 create mode 100644 .changes/v2024.5.23.md
To https://github.com/OpsLevel/cli
 ! [rejected]        HEAD -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/OpsLevel/cli'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.

```